In [14]:
import matplotlib.pyplot as plt
import pandas as pd
import sklearn
import seaborn
import torch
import numpy as np

In [2]:
# form a tensor(multi-dimension matrix, which will sent to the model)
np.set_printoptions(precision=5)
a = [1,2,3]
b = np.array([4, 5, 6], dtype= np.int32)
t_a = torch.tensor(a)
t_b = torch.from_numpy(b)
print(t_b)
print(t_a)

tensor([4, 5, 6], dtype=torch.int32)
tensor([1, 2, 3])


In [3]:
t_ones = torch.ones((2,3),dtype = int)
t_ones.shape

torch.Size([2, 3])

In [4]:
print(t_ones)

tensor([[1, 1, 1],
        [1, 1, 1]])


In [5]:
# form a random tensor
rand_tensor = torch.rand(2,3)
print(rand_tensor)

tensor([[0.7596, 0.0467, 0.8377],
        [0.2853, 0.4994, 0.3627]])


# Manipulate torch type

In [6]:
# change torch dtype
t_a_new = t_a.to(torch.int64)
print(t_a.dtype)


torch.int64


In [7]:
t = torch.rand(2,3)

In [8]:
t = torch.rand(2,3)
t_tr = torch.transpose(t, 0, 1)
t_tr

tensor([[0.5915, 0.3554],
        [0.7538, 0.9882],
        [0.3469, 0.6672]])

In [9]:
# reshape a tensor (from 1 dimension to 2 dimension):
t = torch.zeros(30)
t_reshape = t.reshape(5,6)
t_reshape.shape

torch.Size([5, 6])

In [10]:
# remove the unnecessary dimensions
t = torch.zeros(1,2,1,4,1)
t_sqz = torch.squeeze(t, 4)
print(t_sqz.shape)

torch.Size([1, 2, 1, 4])


# Apply mathematical operations

In [11]:
torch.manual_seed(1)
t1 = 2 * torch.rand(5,2) - 1
t2 = torch.normal(mean = 0, std = 1, size = (5, 2))
t2

tensor([[ 0.8590,  0.7056],
        [-0.3406, -1.2720],
        [-1.1948,  0.0250],
        [-0.7627,  1.3969],
        [-0.3245,  0.2879]])

In [12]:
t3 = torch.multiply(t1, t2)
t3

tensor([[ 0.4426, -0.3114],
        [ 0.0660, -0.5970],
        [ 1.1249,  0.0150],
        [ 0.1569,  0.7107],
        [-0.0451, -0.0352]])

NameError: name 'to' is not defined