In [6]:
import matplotlib.pyplot as plt
import pandas as pd
import sklearn
import seaborn
import torch
import numpy as np

In [7]:
# form a tensor(multi-dimension matrix, which will sent to the model)
np.set_printoptions(precision=5)
a = [1,2,3]
b = np.array([4, 5, 6], dtype= np.int32)
t_a = torch.tensor(a)
t_b = torch.from_numpy(b)
print(t_b)
print(t_a)

tensor([4, 5, 6], dtype=torch.int32)
tensor([1, 2, 3])


In [21]:
t_ones = torch.ones((2,3),dtype = int)
t_ones.shape

torch.Size([2, 3])

In [22]:
print(t_ones)

tensor([[1, 1, 1],
        [1, 1, 1]])


In [36]:
# form a random tensor
rand_tensor = torch.rand(2,3)
print(rand_tensor)

tensor([[0.7531, 0.3898, 0.9838],
        [0.0808, 0.1447, 0.9011]])


# Manipulate torch type

In [40]:
# change torch dtype
t_a_new = t_a.to(torch.int64)
print(t_a.dtype)


torch.int64


In [58]:
t = torch.rand(2,3)
t_tr = torch.transpose(t, 0, 1)
t_tr

tensor([[0.6023, 0.7205],
        [0.3875, 0.8679],
        [0.8265, 0.3855]])

In [65]:
# reshape a tensor (from 1 dimension to 2 dimension):
t = torch.zeros(30)
t_reshape = t.reshape(5,6)
t_reshape.shape

torch.Size([5, 6])

In [ ]:
# remove the unnecessary dimensions
t = torch.t